<?php

require_once ('../approot.inc.php');

$sDbHost = $_POST['db_host'];
$sDbName = $_POST['db_name'];
$sDbUser = $_POST['db_user'];
$sDbPwd = $_POST['db_pwd'];

if (!file_exists(CONFIG_FILE)) {
    echo 'Создаётся файл конфигурации: ' . CONFIG_FILE;

    to_cnf('<?php');
    to_cnf('');
    to_cnf('/**');
    to_cnf('*');
    to_cnf('* Config file, generated by configuration wizard');
    to_cnf('*');
    to_cnf('*/');
    to_cnf('');
    to_cnf('$MySettings = array(');
    to_cnf('');
    to_cnf('// Сервер базы данных');
    to_cnf('// localhost');
    to_cnf("'db_host' => '" . $sDbHost . "',");
    to_cnf('');
    to_cnf('// Имя базы данных');
    to_cnf('// eds');
    to_cnf("'db_name' => '" . $sDbName . "',");
    to_cnf('');
    to_cnf('// Имя пользователя базы данных');
    to_cnf('//');
    to_cnf("'db_user' => '" . $sDbUser . "',");
    to_cnf('');
    to_cnf('// Пароль пользователя базы данных');
    to_cnf('//');
    to_cnf("'db_pwd' => '" . $sDbPwd . "'");
    to_cnf('');
    to_cnf(');');

    chmod(CONFIG_FILE, 0444);

    echo ' - OK';
};
include_once ('./mysql_connect.php');

function to_cnf ($a) {

    //открываем файл для записи.Если файл не существует-он будет создан
    $fopen  =  fopen(CONFIG_FILE, 'a+') or die("не удалось создать файл: ".CONFIG_FILE);
//записываем строку
    fputs ($fopen, $a.PHP_EOL);
//закрываем файл
    fclose ($fopen);

    if (!file_exists(CONFIG_FILE)) {
        echo "Ошибка создания файла";
        die;
    };
};
?>